### ISSUE TITLE
Slice error when writing to rolling opensearch cluster

### ISSUE THREAD

**Issue by godber** [terascope/elasticsearch-assets#970]
We were rolling an internal `1.3.*` Opensearch cluster today and noticed that we started getting slice errors during the roll.  Specifically we were getting this error:

```
class NoLivingConnectionsError extends OpenSearchClientError {
  constructor(message, meta) {
    super(message);
    Error.captureStackTrace(this, NoLivingConnectionsError);
    this.name = 'NoLivingConnectionsError';
    this.message =
      message ||
      'Given the configuration, the ConnectionPool was not able to find a usable Connection for this request.';
    this.meta = meta;
  }
}
```

https://github.com/opensearch-project/opensearch-js/blob/871a6669c9153d8161b3bbbce8747b86f9e6f758/lib/errors.js#L66

**Comment by godber** [comment]
The settings on the connector are

```
          es_os_data1:
            node:
            - http://es-os-data1.qa:9200
            sniffInterval: 60000
            sniffOnConnectionFault: false
            sniffOnStart: false
            suggestCompression: false
```

And the problem isn't just "during roll" ... slice errors can happen AFTER a roll is complete on a job that has been paused, then resumed well after the roll is complete.  The annotations below note when the cluster roll starts and is completed:

<img width="339" alt="Screen Shot 2022-11-08 at 4 22 53 PM" src="https://user-images.githubusercontent.com/1249/200697479-6c0c5d77-904c-497e-b804-4be7e758ce60.png">

So it's like the client behavior has changed and we need to set `sniffOnConnectionFault: true` now.

Realistically, this is not that big of a surprise that a behavior like this would change.  We'll test these scenarios when someone frees up.
